windowrulev2 = noblur 0, class:^(wayland)$
windowrulev2 = float, class:^(feh)$
windowrulev2 = move onscreen cursor -100% -100%, class:^(feh)$
windowrulev2 = float, class:^(org.kde.kalk)$
windowrulev2 = float, class:^(qalculate-gtk)$
windowrulev2 = noanim, class:^(flameshot)$
windowrulev2 = move 0 0,class:(flameshot),title:(flameshot)
windowrulev2 = pin,class:(flameshot),title:(flameshot)
windowrulev2 = fullscreenstate,class:(flameshot),title:(flameshot)
windowrulev2 = float,class:(flameshot),title:(flameshot)

windowrulev2 = float, class:^(foot)$,title:^(terminal filechooser)$
windowrulev2 = size 60% 65%, class:^(foot)$,title:^(terminal filechooser)$

windowrulev2 = workspace special:discord, class:^($discord)$
windowrulev2 = workspace special:top, class:^($terminal)$, title:^($top)$

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

workspace = special:email, on-created-empty:$email
workspace = special:discord, on-created-empty:$discord
workspace = special:spotify, on-created-empty:$spotify
workspace = special:top, on-created-empty:$top
workspace = special:terminal, on-created-empty:[float]$terminal

# dynamically added float rules
windowrulev2 = float, class:^(zen)$, initialTitle:^(Parent process Browser Console)$
windowrulev2 = float, class:^(zen)$, initialTitle:^(Library)$
windowrulev2 = float, class:^(zen)$, initialTitle:^(Picture-in-Picture)$
windowrulev2 = float, class:^(zen)$, initialTitle:^()$
windowrulev2 = float, class:^(flameshot)$, initialTitle:^(Configuration)$
windowrulev2 = float, class:^(flameshot)$, initialTitle:^(flameshot-pin)$
