[main]
include=~/.config/foot/themes/dark-pastels
font=monospace:size=11.5

[colors]
alpha=0.9

[key-bindings]
clipboard-paste=Alt+p XF86Paste Control+Shift+v
# meant to be some irrelevent key
spawn-terminal=Control+Alt+Shift+p
