[main]
include=~/.config/foot/themes/dark-pastels
font=monospace:size=11.5

[colors]
alpha=0.9

[key-bindings]
clipboard-paste=Alt+p XF86Paste Control+Shift+v
clipboard-copy=Alt+Return XF86Copy Control+Shift+c
# meant to be some irrelevent key
spawn-terminal=Control+Alt+Shift+p
search-start=Alt+slash
scrollback-up-half-page=Alt+u
scrollback-down-half-page=Alt+d

[search-bindings]
delete-to-end=Control+d
find-prev=Control+p
find-next=Control+n
cursor-left=Left
cursor-left-word=Alt+b
cursor-right-word=Alt+f
extend-line-down=Control+j
extend-line-up=Control+k
extend-char=Control+l
extend-backward-char=Control+h
extend-backward-to-word-boundary=Control+b
